### PR TITLE
suggestion: make repository python package ready

### PR DESCRIPTION
**Pull request by blondegeek**
Hello,

If you're interested, I've made a few small changes to the organization of your repository so it can be easily installed as a python package (eg: pip install -e git+https://github.com/deworrall92/harmonicConvolutions.git#egg=harmonicconvolutions). 

Any scripts that were referenced by other scripts, I've placed in the harmonicconvolutions package subfolder with an __init__.py. Otherwise, I've left the script in the original folder. I've also added a setup.py that you may want to modify to include additional requirements.

I have only tested that the train.py command in the repository README.md is functioning after the changes.

Thanks!
Tess

### CODE REVIEW

**Comment by StephanGarbin** [comment]
Hi Tess,

Thank you for that, I will look into compatibility of this with some of our latest changes next week.

Best
Stephan

**Comment by isaacgerg** [comment]
Does this work with tf 1.3?

**Comment by StephanGarbin** [comment]
We unfortunately haven’t had the time to investigate the compatibility of this pull request with tensorflow 1.3. This relates to an older version of the code in any case that isn’t supported anymore.
At this stage we advise just cloning the repo and referencing it in your scripts.
Hope that helps!

**Comment by isaacgerg** [comment]
I was actually able to upgrade it to tf 1.3.  Would you like the diff?

**Pull request closed without merging**
